list: $/militarymi/kindergarten/models/departament/columns.yaml
modelClass: Militarymi\Kindergarten\Models\Departament
title: Departaments
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'militarymi/kindergarten/departaments/update/:id'
