list: $/militarymi/kindergarten/models/personaljobposition/columns.yaml
modelClass: Militarymi\Kindergarten\Models\PersonalJobPosition
title: JobPosition
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'militarymi/kindergarten/jobposition/update/:id'
