title: Service
modelClass: Militarymi\Kindergarten\Models\Service
list: $/militarymi/kindergarten/models/service/columns.yaml
recordUrl: 'militarymi/kindergarten/service/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
